config/routes.rb
Rails.application.routes.draw do
  resources :youtubes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/youtubes_controller.rb
class YoutubesController < ApplicationController
  # GOOGLE_API_KEY = Rails.application.credentials.google[:api_key]
  # GOOGLE_API_KEY = AIzaSyAnKVFg0CE4X7OhzOe3ZfD23d4IaBAH6uc

  # binding.pry

  def find_videos(keyword, after: 1.months.ago, before: Time.now)
    service = Google::Apis::YoutubeV3::YouTubeService.new
    service.key = ENV["YOUTUBE_APIKEY"]
    # service.key = AIzaSyAnKVFg0CE4X7OhzOe3ZfD23d4IaBAH6uc

    next_page_token = nil
    opt = {
      q: keyword,
      type: 'video',
      max_results: 10,
      order: :relevance,
      page_token: next_page_token,
      published_after: after.iso8601,
      published_before: before.iso8601
    }
    service.list_searches(:snippet, opt)
  end

  def index
    @youtube_data = find_videos(params[:title])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/youtubes_helper.rb
module YoutubesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoutubesearchApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/youtubes/index.html.erb
<%= link_to 'New User', youtubes_path, remote: true, class: "btn btn-lg, btn-primary" %>







<h1>youtube</h1></h1>
<%= form_with(url:youtubes_path, local: true, method: :get) do |form| %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<% @youtube_data.items.each do |item| %>
  <% snippet = item.snippet %>
  <p><%= snippet.title %></p>
  <p><%= snippet.published_at %><%= snippet.channel_title %></p>
  <div><iframe width="900" height="600" src="https://www.youtube.com/embed/<%= item.id.video_id %>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>
<% end %>

app/views/youtubes/index.js.erb
$("#user-modal").html("<%= escape_javascript(render 'form') %>")
$("#user-modal").modal("show")